### ISSUE TITLE
Midweek hangouts call?

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/apprenticeship#12]
@finnhodgkin and I would like to have a call with @iteles and @nelsonic midway through this (week beginning 10/7/17) week to discuss how the apprenticeship is going, and where our future with dwyl lies. This relates to #7 but we would really value a verbal communication so that we can consider how things will progress.

We are both away the 3 weeks following this week, but would like to discuss the possibility of continuation after this.

Would Thursday 13/7/17 be good? I am happy to take minutes from the discussion and comment them in this issue so that nothing that is discussed is lost.

**Comment by nelsonic** [comment]
@ZooeyMiller Yes, Thursday looks good. what time?

**Comment by ZooeyMiller** [comment]
@nelsonic any time between 9:00 and 18:00 is fine for me. How about 14:00?

**Comment by ZooeyMiller** [comment]
All good for 14:00 today? @nelsonic

**Comment by ZooeyMiller** [comment]
hangouts link sent on gitter to @nelsonic

**Comment by ZooeyMiller** [comment]
Left the hangouts to get on with some work as had no confirmation. Please let us know when you're free @iteles @nelsonic

**Comment by finnhodgkin** [comment]
@nelsonic Are you around for this any time today?

It's the last day of our four weeks :sob:

**Comment by nelsonic** [comment]
@finnhodgkin free now?

**Comment by iteles** [comment]
This was covered in #16 👍
