### ISSUE TITLE
Working through learn-aws-lambda

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/apprenticeship#13]
@finnhodgkin and I will be working through `learn-aws-lambda` today, this morning we have been working on issues in `learn-amazon-web-services` with time estimates in the issues on that repo.

I am estimating a day for `learn-aws-lambda` as it looks like quite a long repo. Any issues we raise will be individually time estimated as well and those time estimates are not necessarily contained in the day assigned to this issue. 

EDIT: Due to overrunning the day time estimate, each of these chapters in `learn-aws-lambda` (apart from the ones already completed) will be made as individual issues and time estimated on their own.

- [ ] Create a Lambda function inline - done, 25m
- [ ] Create a Lambda function using a .zip folder - done, 25m
- [ ] Create a Lambda function using the AWS API Gateway - done, ~5h
- [ ] ~Trigger a Lambda function using an event from DynamoDB~
- [ ] ~Trigger a Lambda function using the Simple Notification System~
- [ ] ~Continuous Integration using Codeship~
- [ ] ~Testing Lambda Functions~
- [ ] ~Upload Lambda Function to S3 and deploy to Lambda~
- [ ] ~Deploying Lambda Functions using Gulp~
- [ ] ~Versioning and Aliasing Lambda Functions~
- [ ] ~Create an API with GET/POST Methods using Lambda functions to retrieve/update records from a DynamoDB table~

We've struck through these parts as they are not relevant to the things mentioned in https://github.com/dwyl/apprenticeship/issues/13#issuecomment-314486997 so today will be working on:
+ [ ] Calling that Lambda Function when an email is _received_ via SES. https://github.com/dwyl/learn-aws-lambda/issues/97
+ [ ] Save the body of the email to S3 (_the easiest for now..._) https://github.com/dwyl/learn-aws-lambda/issues/98

Neither of these are already in the repo so we will have to make them from scratch.

**Comment by ZooeyMiller** [comment]
Our time estimate has been way off. We expected this to take 1 day but it is definitely going to take longer. We're currently around 1/4 of the way through due to doing a lot of independent research. Hopefully 2 days will be enough.

**Comment by nelsonic** [comment]
@ZooeyMiller when ever you think an estimate is going to take longer than `T1d` (_our [max time estimate label](https://github.com/dwyl/labels/labels)_) you know it's time to split it out into smaller issues/stories with detailed checklists. 👍

**Comment by finnhodgkin** [comment]
The aws API is not my favourite...

It seems like most of the code in this repo is out of date so most sections will need a fair bit of updating.

**Comment by ZooeyMiller** [comment]
@nelsonic apologies, I misinterpreted the `t[x]d` definition in https://github.com/dwyl/labels as meaning it was okay to create more time estimates, but will make sure not to in future :+1:

**Comment by nelsonic** [comment]
@finnhodgkin if _a lot_ is out-of-date, please only update the bits that are relevant to:
+ [ ] Creating a Lambda Function
+ [ ] Calling that Lambda Function when an email is _received_ via SES.
+ [ ] Save the body of the email to S3 (_the easiest for now..._)

For context, we are going to be working on this: https://github.com/dwyl/aws-ses-lambda _soon_ hence wanting to update the Lambda-related knowledge. 😉

**Comment by finnhodgkin** [comment]
'A fair bit' was probs an exaggeration. 

The menus have changed a little, but not so much that we should re-write the whole thing. The main change is in JS syntax - context.succeed() has been replaced by error first callbacks.

**Comment by nelsonic** [comment]
@finnhodgkin yeah, the callback syntax is preferable but _both_ are still valid. 😉 
(_if you have time to update and/or add a paragraph to `.md` file informing people that would be ace!_)

**Comment by finnhodgkin** [comment]
@nelsonic oh that's strange- I was getting errors with context.succeed(). I'll check again when I get in to make sure it's not some other error, but the aws docs do say:

> We strongly recommend updating any use of the context method and replacing it with the callback approach. 

There's actually already a paragraph in there about callbacks vs context but it's quite far down the page. Might make more sense to move it up to the top.

**Comment by finnhodgkin** [comment]
Update: context.done/succeed definitely do still work so it must have been some other error. 

Still worth converting all the snippets to callbacks at some point given the above recommendation from Amazon.

**Comment by finnhodgkin** [comment]
I'm currently researching how to call a lambda when SES receives mail. There's nothing in learn-aws-lambda about SES so it's all new info :+1:  

Info here: https://github.com/dwyl/learn-aws-lambda/issues/97

**Comment by ZooeyMiller** [comment]
@nelsonic with regards to https://github.com/dwyl/learn-aws-lambda/issues/97#issuecomment-314718709 what should @finnhodgkin and I work on in the meantime?

**Comment by finnhodgkin** [comment]
While we wait for a response we'll go through `aws-sdk-mock` as suggested https://github.com/dwyl/apprenticeship/issues/10

**Comment by finnhodgkin** [comment]
We've done the thing where an email triggers a lambda function, but we're not :100:% clear that it's actually running. To test it we're going to make the lambda save something to S3, and then if that works we'll get the email body.

:+1:

**Comment by nelsonic** [comment]
I've recently used the guid to deploy a Lambda: https://github.com/nelsonic/github-scraper/issues/128 🚀 
Worked well. ✅ 
Closing as no further action on this issue. 📕
