### ISSUE TITLE
Playing with asw-sdk-mock

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/apprenticeship#15]
With reference to #10 we are supposed to be looking into updating the [`aws-sdk-mock`](https://github.com/dwyl/aws-sdk-mock) module, but we have no experience of it, so we want to write some tests using it to get some hands on experience before we attempt to update the documentation or fix the issues.

**Comment by ZooeyMiller** [comment]
see this repo in my github for reference: https://github.com/ZooeyMiller/aws-mock-practice

**Comment by ZooeyMiller** [comment]
Having played around in the repo linked above :arrow_up: we feel comfortable with the basics of `aws-sdk-mock` and using sinon spies with it as well, so we are going to move on to having a look at the issues and such on the repo.

**Comment by nelsonic** [comment]
@ZooeyMiller great stuff! it would be _amaze_ if you had time to improve it. 👍
