### ISSUE TITLE
Apprenticeship debrief

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/apprenticeship#16]
@ZooeyMiller and I would really like to have a discussion about how the apprenticeship has gone and how we can move forward from it, especially considering that the original four week apprenticeship is now over. It was really unfortunate that we couldn't have that chat yesterday (#12) but how would Monday at 9am be for you. @ZooeyMiller is mentoring all next week so he can only do morning or lunch.

@iteles @nelsonic

**Comment by nelsonic** [comment]
@finnhodgkin if you're available now, I'm on the dwyl standup hangout: 
https://hangouts.google.com/hangouts/_/dwyl.com/standup
@iteles is in a sprint-planning meeting (_hangout_) so if you prefer 13:00 let us know! 👍

**Comment by nelsonic** [comment]
BTW: our preferred way to debrief is a Pull Request improving the repo 
e.g: if you could design an "awesome apprenticeship experience" what would it be? 😉

**Comment by finnhodgkin** [comment]
Sorry I woke up a bit late today so I'm only just on the train 😴. 13:00 is definitely better for me! I'll check with Zooey to make sure he can make it then too 👍

**Comment by nelsonic** [comment]
Cool sending you Calendar invite now (_so everyone gets a reminder_) 🕐

**Comment by ZooeyMiller** [comment]
13:00 all good for me :+1:

**Comment by nelsonic** [comment]
https://hangouts.google.com/hangouts/_/dwyl.com/standup

**Comment by ZooeyMiller** [comment]
@nelsonic trying to join but it's just hanging?

**Comment by nelsonic** [comment]
Hangouts is complaining about bandwidth ... 😞 
![image](https://user-images.githubusercontent.com/194400/28267259-323ec304-6af1-11e7-9f41-958fd07915f5.png)
(probably has something to do with @iteles being on another Hangout call ..._)

**Comment by ZooeyMiller** [comment]
Closing this issue since the call happened :+1:

**Comment by iteles** [comment]
@ZooeyMiller Any learnings/improvements/interesting points raised?

**Comment by ZooeyMiller** [comment]
@iteles The main points were that we will be able to continue our work with dwyl, and that when @finnhodgkin and I have time we will raise issues and make a PR to the apprenticeship repo with ways we feel the process can be improved for potential new apprentices.
