### ISSUE TITLE
Increase in rates over time

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/apprenticeship#17]
After having the hangouts call with @nelsonic (#16) we've established that @finnhodgkin and I can continue working with dwyl :tada: :sparkles: which is awesome.

During the call I asked about an increase in rates from the £75/day that we've been on for the past 4 weeks. 

We were pointed towards @sofer and @iteles to ask this question, hence this issue being raised.

Is there scope for these rates to be increased? If so, what to, and is there a plan for how they may increase over time? Perhaps akin to the way described in https://github.com/foundersandcoders/freelancing/blob/master/rates.md

I speak only for myself now (not Finn) but due to mentoring commitments for Founders and Coders I will not be available for full time work until Monday 7th August. 

In a related but not the _same_ note, in our continued work for dwyl, will we be considered apprentices still, or general contractors? (would be nice to update linkedin etc to something like "full stack web developer @dwyl" if it's the latter).

**Comment by iteles** [comment]
@ZooeyMiller I will be catching up with @nelsonic to understand exactly what you will be working on and what the impact of this is for dwyl and will get back to you with answers on this 👍

**Comment by ZooeyMiller** [comment]
That's awesome, thank you for your swift response :pray:

**Comment by finnhodgkin** [comment]
You may as well have been speaking for me @ZooeyMiller :+1: My availability is the exactly the same - I'm not mentoring this week but I have a bunch to do before we fly on Saturday. We actually land at 1am on the  7th so I doubt we'll be all that ready for work on the Monday morning :sleeping: 

Thanks @iteles

**Comment by iteles** [comment]
These were increased in September 👍 
A _lot_ more clarity is needed on the apprenticeship generally for future apprentices!
