### ISSUE TITLE
Update on my Plans

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/apprenticeship#18]
Hi :wave: 

Unsure of where specifically to put this, but this repo seems the main place for communication RE: mine and Finn's work stuff. 

I'm going to be staying in the Middle East a little longer so week beginning the 7th I was hoping to work remotely from Nazareth (for the whole week, Mon-Fri), and then the following week I will be in Gaza, and was hoping to work 3 days for dwyl if possible (Tuesday, Wednesday, Friday). In Gaza I'm helping mentor as Elias needs to spend more time on QA, so more support is needed here. 

Please let me know how this fits in with what you're planning for Finn and I to be working on, and if it's all okay. 

Hope you're all having a lovely time by the lake!

@nelsonic @iteles

**Comment by finnhodgkin** [comment]
Just to be clear I'm sadly _not_ hanging around in the middle east and will still be back on Monday :+1:

**Comment by nelsonic** [comment]
Hi @ZooeyMiller & @finnhodgkin thanks for sharing your plans.
As you may be aware, Ines and I will be "_off_" for next couple weeks. 
Have either of you made a stab at learning some Elixir? 💭

**Comment by ZooeyMiller** [comment]
@nelsonic Yeah of course! Is there a point person for us during our continued work whilst you and Ines are away? 

Are we still set to start working again on the 7th as mentioned in #17 ?

I've done a bit of Elixir but haven't moved onto Phoenix yet. Looking to do the Stephen Grider's Udemy course on Phoenix/Elixir when I have some time.

**Comment by iteles** [comment]
Honestly, everyone is pretty stretched in our absence next week as there are at least 4 of us on holiday. Would it be possible to start again on 14th?

**Comment by ZooeyMiller** [comment]
@iteles of course! No problem :) I will be mentoring all day on the 14th but happy to get started on the 15th. 

Have a wonderful weekend! :cake: :sparkles:

**Comment by finnhodgkin** [comment]
@iteles Of course that's fine by me too. 😊

Have an __amazing__ day today! 🎉💃🏻🕺🏿

**Comment by finnhodgkin** [comment]
Hi guys, hope you had a lovely weekend :smile:

It's starting day today :tada: Is there anything in particular you want me to work on? @ZooeyMiller isn't around until tomorrow so it might be worth holding off on starting a longer project (if there is one).

I'll make a start on the Stephen Grider Elixir and Phoenix series while I wait for a response, plus there were a few PRs to make before I left for Nazareth :+1:

**Comment by ZooeyMiller** [comment]
I'm going to carry on with the Stephen Grider course while I wait for direction too, will look over the `learn-elixir` repo to see if there are any updates I can make, but some direction/information on pay/contract would be really appreciated!

**Comment by ghost** [comment]
@nelsonic @iteles welcome back from the honeymoon! 🎉 

Do you have specific plans for @finnhodgkin and @ZooeyMiller or should they continue as they are or do you mind if I assign them work? Let me know as soon as possible please!

**Comment by iteles** [comment]
@finnhodgkin @ZooeyMiller We're not actually back from honeymoon yet, still officially off!

I would suggest you spend the week laser focused on learning Elixir and enhancing `learn-elixir` where you can. Also take a look at https://github.com/healthlocker that @katbow and @RobStallion and arm yourselves to become Elixir fiends so that you can 10x your developer powers!

**Comment by ZooeyMiller** [comment]
Awesome! Thank you for getting back to us while you're still on you honeymoon, enjoy it! :dark_sunglasses: :sparkles: :sun_with_face:

**Comment by finnhodgkin** [comment]
Thanks @iteles, laser elixir sounds perfect :ok_hand: At some point when you're settled could we have a hangouts about boring contract things?

Sorry to disturb your honeymoon, hope you're have an amazing time! :tada:

**Comment by ghost** [comment]
@iteles in response to https://github.com/dwyl/apprenticeship/issues/18#issuecomment-322438920

When are you back? Katy and Mollie were expecting @nelsonic to be working on Oxleas this morning

**Comment by iteles** [comment]
@markwilliamfirth As you know, Nelson is providing support for Oxleas for 0.5 days across this week and next week. Neither Nelson nor I set the expectation you mention above. This is also not the right thread for that conversation.

**Comment by ghost** [comment]
@iteles wasn't aware of this until we spoke 20 minutes ago - thanks for updating GH too 👍

**Comment by ghost** [comment]
- Confirmed that Finn and Zooey should continue to learn Elixir and enhance the learn-elixir repo
- Following that look into and familiarise themselves with https://github.com/healthlocker (an example of a dwyl elixir project)
- Plus completing and updating any outstanding issues in this repo
