### ISSUE TITLE
How to make a "Real" Tutorial ?

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/apprenticeship#29]
Even after some weeks reading several tutorials I still can't understand why there are tutorials for the same subject that differ so much from each other.
Tutorials full of information but that make the learning experience "boring" because they don't go straight to the subject making us waste precious time, as tutorials that have little information more than after reading them we still have more doubts than before we read it.

What aspects are important for the creation of a tutorial ?
A tutorial that stands out from others and allows the user or "student" a better absorption of the knowledge put in that tutorial.

Should it be a long tutorial (complete) or should we simplify the code/text as much as possible without losing necessary information?

**Comment by nelsonic** [comment]
Plenty of real tutorials: 
https://github.com/dwyl/technology-stack/blob/df28b38a2962bc286bcd5131ca8fa1d63be2b90e/README.md#beginner-tutorials

Closing. ✅
