### ISSUE TITLE
My availability

### ISSUE THREAD

**Issue by mattlub** [dwyl/apprenticeship#4]
Hi @nelsonic,

As I mentioned I was considering last week, I have just confirmed I will be heading back out to Nazareth for a month at the end of this week to help with the start of the next F&C course, so unfortunately won't be around for the apprenticeship over the next few weeks.

Apologies for the late notice- I've been in Glastonbury for the last few days and hadn't got around to finalising with Dan. I should be around over this week so I'll come to speak to you guys if you're about.

I'll keep in contact and keep contributing :)

Matt

**Comment by iteles** [comment]
@mattlub Thank you for letting us know! It's a real shame (for us) and a real gain (for Nazareth). ❤️ 

Hope Glastonbury was awesome and let's stay in touch!
