### ISSUE TITLE
Standups?

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/apprenticeship#5]
What is the plan with standups when the apprentices or the mentors are working remotely?
(or just aren't in one of the Palmer's Road offices)

I've found days without some kind of chat in the morning about the goals for the day quite difficult as I'm not _really_ sure what I should be doing, and can end up feeling a little directionless, and unsure of how to prioritise my time, and as such I have felt unproductive.

I know that I personally would benefit from a chat with the person mentoring the apprenticeship every day, just to clarify goals for the day, but any clarification would be ace.

**Comment by nelsonic** [comment]
@ZooeyMiller _another_ great question. 
We have typically done standup via Hangouts but are open to suggestions because we think it's sub-optimal as it does not _capture_ the info ...

**Comment by ZooeyMiller** [comment]
@nelsonic hangouts are a good shout for the moment I guess. I suppose ideally there would be am minute taker during the standup who could record what was said.

Could we start doing some via hangouts then? I'm not sure of how to organise or who should be present for the apprenticeship standups but I feel it would be super beneficial.

**Comment by nelsonic** [comment]
GOTO: https://github.com/dwyl/apprenticeship/tree/e05366c779d94597076a93f84c76321a90719a2f#q-how-to-communicate
