### ISSUE TITLE
Communication method?

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/apprenticeship#6]
What is the best communication method should apprentices be using to communicate with mentors?
And who can/should I be communicating with?

I mean aside from Github. Github is great for communication but sometimes things that I do not want to post publicly affect my working life, I have been trying gitter as I see it as a work based communication tool, but it doesn't seem to be being used very much.

**Comment by finnhodgkin** [comment]
Hopefully [chat](https://github.com/dwyl/chat) in the future :heart_eyes:

**Comment by nelsonic** [comment]
gents, yes, in the _future_ chat, but for now issues. 👍

**Comment by ghost** [comment]
@nelsonic I think Zooey also wanted clarification on the best way to communicate urgent things not suitable for public posting in issues? (as a stopgap until chat is made)

**Comment by ZooeyMiller** [comment]
Thanks @markwilliamfirth yes I generally meant more urgent things, is SMS okay if it's more private/urgent @nelsonic ?

**Comment by ghost** [comment]
@nelsonic would you be able to confirm this? When I try and call it just bleeps and I haven't received any SMS responses.

**Comment by nelsonic** [comment]
When an SMS is something `urgent` I reply. ✅ 
For _everything_ `else` issues. :octocat: 🎉

**Comment by ghost** [comment]
Closing as this was answered!
