### ISSUE TITLE
What I'm working on right now

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/apprenticeship#8]
The last thing I know I need to finish is https://github.com/dwyl/learn-WebRTC/issues/5 and as said in that issue, I am waiting for @finnhodgkin to be free from his mentoring commitments at Founders and Coders so that we can pair on it.

Under the advice of @sohilpandya I am learning Elixir in the meantime, with Elixir School (as advised by @nelsonic of the resource to use). 

I know that I/we are supposed to be directing efforts towards [chat](https://github.com/dwyl/chat) but it would be good to have some more concrete direction on what we/I should be working on in chat before cracking on with it. 

If anyone is available today to talk through goals for the rest of this week that would be greatly appreciated.

**Comment by ZooeyMiller** [comment]
I am in the same position today. Since it is a project day at founders and coders @finnhodgkin and I will pair on the css and finish the PR to learn-WebRTC and then continue with Elixir I suppose until given further direction.

**Comment by ZooeyMiller** [comment]
Having not been specifically directed and after an in person communication with @shouston3 we (@finnhodgkin and I) have decided to work on an actualisation of the `chat` in some sense. 
See https://github.com/dwyl/chat/issues/41 for more details

**Comment by nelsonic** [comment]
@ZooeyMiller this sounds good for today. 👍 
I've also created https://github.com/dwyl/apprenticeship/issues/10 in case you want to try your hand at AWS. (_leave a comment on the issue if interested_) 👍
